### PR TITLE
Fix #2

### LINKED ISSUE #2: Support nested fragments
We currently only process immediate fragments within a template. We should recursively process fragments.

### PR DESCRIPTION
**Pull request by lknop**
This PR fixes #2 adding support for nested fragments in the templates

### CODE REVIEW

**Comment by markhobson** [comment]
Thanks for the PR. Could you also add a test for nested fragments please?

**Comment by lknop** [comment]
Sure, that's a good idea. I also have a fix to break out of recursion when there are mistakes in the definitions, I'll add that too.

**Comment by lknop** [comment]
I set the maximum level of nesting to 5. Unfortunately I needed to add a `browser.wait` in the test since sometimes the browser did manage to load all the content but sometimes it did not, waiting makes it 100% reliable.

**Comment by markhobson** [comment]
Thanks for this PR @lknop and apologies for the delay in getting around to looking at it. I've pushed back a slightly different implementation based on your submission:

* To fix the tests asserting the page before it has been fully processed I introduced a script that is run after `thymeleaf-fragment.js` that adds a CSS class to the body. The tests then wait for this to be present before asserting. This has the advantages that it tests the `holdReady` part of the implementation and that tests don't need custom wait conditions.
* I implemented the recursion with a breadth-first traversal of fragments rather than depth-first. This simplified the code and I believe will optimise the loading time.

Let me know if you encounter any problems with this implementation.

**Pull request closed without merging**
